spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1/working_tool_bot
application:
  bot:
    username: BscWorkingToolBot
    token: 6236403942:AAEHWlA-9DNUygECvgBIgCyM1RekaXspw7Q
server:
  port: 8095